routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) 
    {
        return redirect()->route('anuncio.index');
    }

    else
    {
        return view('welcome');
    }
    
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/produto', 'ProdutoController')->middleware('auth');

Route::resource('/anuncio', 'AnuncioController')->middleware('auth');

Route::get('/lixeira', 'AnuncioController@showTrashed')->name('lixeira');

resources/views/anuncio.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/anuncio.css') }}">
@endsection

@section('navbar')

    @include('layouts.navbar')

@endsection

@section('content')

<div class="container" id = "ad">  

        <div class="row">

            <div class="col m12">

                <div class="card large">

                    <div class="card-content">
                        
                        <h5>
                            Cadastrar Anúncio
                        </h5>

                        <form action = "{{ route('anuncio.store') }}" method="POST" enctype="multipart/form-data" id ="formulario-anuncio">
                            @csrf
                            <div class="col m6">

                                <div class="input-field col m12">
                                    <input name="nome" type="text" class="validate" id = "nome" v-model="nome">
                                    <label for="nome">Nome</label>
                                </div>

                                <div class="input-field col m12">
                                    <textarea class="materialize-textarea" name="descricao" id = "descricao" v-model="descricao"></textarea>
                                    <label for="textarea1">Descrição do anúncio</label>
                                </div>

                                <div class="input-field col m12">
                                    <input name="link" type="text" v-model="link">
                                    <label for="link">Link do produto</label>
                                </div>

                            </div>

                            <div class="col m6"> 

                                <div class="file-field input-field col m12">
                                    <div class="btn btn-small orange darken-1 shadow-xm">
                                        <span>Imagem</span>
                                        <input type="file" name="imagem_produto" id = "input-image" v-on:change = "loadImage">
                                    </div>

                                    <div class="file-path-wrapper">
                                        <input class="file-path" type="text" name="caminho_imagem" id="caminho_imagem" placeholder="Escolha a imagem do produto" v-on:change="getFields">
                                    </div>
                                </div>

                                @foreach($estados as $estado)
                                    <div class="col m3">
                                        <p>
                                            <label class="text-orange">
                                                <input type="checkbox" checked="checked"/>
                                                <span> {{ $estado }} </span>
                                            </label>
                                        </p>
                                    </div>
                                @endforeach

                            </div>

                            <div class="col m12 center">
                                <a class="btn-small orange darken-1" v-on:click="showTemplate">Visualizar</a>
                                <a class="btn-small orange darken-1" v-on:click="validateAd">Cadastrar Anúncio</a>
                            </div>

                        </form>

                        <div class="col m4 offset-m4" v-if="mostra">
                            
                            <div class="card small">
                                <div class="card-image imagem">
                                    <img class="activator" src="{{ asset('img/logo.png') }}">
                                </div>

                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">@{{ nome }}<i class="material-icons right">more_vert</i></span>

                                    <div class="col mt-1">
                                        <a v-bind:href=" 'https://' + link" target="_blank"> @{{ nome }} </a>
                                    </div>

                                    <div class="col right mt-1">
                                        <span class="new badge green right-align tooltipped" data-position="bottom" data-tooltip="Data de Criação" v-bind:data-badge-caption="data_criacao"></span>
                                    </div>
                                </div>

                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">@{{ nome }}<i class="material-icons right">close</i></span>
                                    <p> @{{ descricao }} </p>
                                </div>
                            </div>
                        </div>
                </div>

            </div>
        </div>
</div>

@endsection

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/dashboard.css') }}">
@endsection

@section('navbar')

    @include('layouts.navbar')

@endsection

@section('content')
<div class="container">
    <div class="row clearfix">
        @if(!$anuncios->isEmpty())
            @foreach($anuncios as $anuncio)
                <div class="col m4" style="margin-top:0.8%">
                    <div class="card medium">
                        <div class="card-image">
                            <img class="activator" src="{{ asset($anuncio->caminho_imagem) }}">
                        </div>

                        <div class="card-content">
                            <span class="card-title activator grey-text text-darken-4">{{ $anuncio->nome }}<i class="material-icons right">more_vert</i></span>
                            
                            <div class="col">
                                <a href="{{'https://' . $anuncio->link }}" target="_blank"> {{ $anuncio->nome }} </a>
                            </div>

                            <div class="col right mt-1">
                                <span class="new badge green right-align tooltipped" data-position="bottom" data-tooltip="Data de criação" data-badge-caption="{{ str_replace('-', '/', date('d-m-Y', strtotime($anuncio->data_criacao))) }}"></span>
                                @if(Auth::check())
                                    <span class="tooltipped" data-position="bottom" data-tooltip="Editar anúncio">
                                        <a href="{{ route('anuncio.show', $anuncio->id)}}">
                                            <i class="material-icons">create</i>            
                                        </a>
                                    </span>
                                @endif

                                @if(Auth::check())
                                    <span class="tooltipped" data-position="bottom" data-tooltip="Excluir Anúncio">
                                        <a href="#DesejaRemover" class="modal-trigger" href="#" v-on:click = "setModalId">
                                            <i class="material-icons right-align">delete</i>
                                        </a>
                                        <form id = "{{ $anuncio->id }}" action="{{ route('anuncio.destroy', $anuncio) }}" method="POST">
                                            @Method('DELETE')
                                            @CSRF
                                        </form>
                                    </span>
                                @endif
                            </div>

                        </div>

                        <div class="card-reveal">
                            <span class="card-title grey-text text-darken-4">{{ $anuncio->nome }}<i class="material-icons right">close</i></span>
                            <p>{{ $anuncio->descricao }}</p>
                        </div>
                    </div>
                </div>
            @endforeach
        @endif

        @if(!$anuncios->count())
            <div class="col m8 offset-m2">
                <div class="card small">
                    <div class="card-content center">
                        <p>Não há nenhum anúncio cadastrado.<p>
                    </div>  
                </div>
            </div>
        @endif
        <input type="hidden" value = "{{ redirectStatus }}" v-on:change="dashboardAlerts" />
    </div>
</div>

<div id="DesejaRemover" class="modal">
    <div class="modal-content">
        <h4 class="orange-text  text-darken-2">Deseja remover o anúncio?</h4>
        <p class="text-darken-2">Atenção! Ao remover o anúncio não será possível reutiliza-lo.</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="modal-close btn btn-small waves-effect">Cancelar</a>
        <a href="#" class="btn btn-small red waves-effect" id="modalRemover" v-on:click="deleteAd">Remover</a>
    </div>
    <input type="hidden" value="" id="idAnuncio">
</div>

@endsection

resources/views/dashboardold.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/dashboard.css') }}">
@endsection

@section('navbar')

    @include('layouts.navbar')

@endsection

@section('content')
        <div class="container">
            <div class="row">
            @if(!$anuncios1->isEmpty())
                @method('DELETE')
                <div class="col m6" style="margin-top:0.8%">
                    @foreach($anuncios1 as $anuncio1)
                        <div class="card horizontal">

                            <div class="imagem valign-wrapper">
                                <img src="{{ asset('storage/' . $anuncio1->caminho_imagem) }}">
                            </div>

                            <div class="anuncio">
                                <h6>{{ $anuncio1->nome }}</h6>

                                <div class="card-content anuncio-conteudo">
                                    <p class="flow-text">{{ $anuncio1->descricao }}</p>
                                </div>

                                <div class="anuncio-link">

                                    <div class="col" style="padding-left:0px;">
                                        <a class="tooltipped" data-position="bottom" data-tooltip="Visitar" target="_blank" href ="{{'http://' . $anuncio1->link }}"> {{ $anuncio1->nome }} </a>
                                    </div>
                                    
                                    <div class="col right">
                                        <span class="new badge red tooltipped" data-position="bottom" data-tooltip="Data final" data-badge-caption="{{ str_replace('-', '/', date('d-m-Y', strtotime($anuncio1->data_fim))) }}"></span>
                                        <span class="new badge green tooltipped" data-position="bottom" data-tooltip="Data inicial" data-badge-caption="{{ str_replace('-', '/', date('d-m-Y', strtotime($anuncio1->data_inicio))) }}"></span>
                                        @if(Auth::check() && !$trashed)
                                            <span class="tooltipped" data-position="bottom" data-tooltip="Editar anúncio">
                                                <a href="{{ route('anuncio.edit', $anuncio1->id)}}">
                                                    <i class="material-icons">create</i>            
                                                </a>
                                            </span>
                                        @endif
                            
                                        <span class="tooltipped" data-position="bottom" data-tooltip="Excluir Anúncio">
                                            @if(Auth::check() && !$trashed)
                                                <a href="#" v-on:click = "deleteAd">
                                                    <i class="material-icons right-align">delete</i>
                                                </a>
                                            @endif
                                            <form id = "{{ $anuncio1->id }}" action="{{ route('anuncio.destroy', $anuncio1) }}" method="POST">
                                                @Method('DELETE')
                                                @CSRF
                                            </form>
                                        </span>
                                    </div>
                                    
                                </div>
                            </div>  

                        </div>
                    @endforeach
                </div>
            @endif

            @if(!$anuncios2->isEmpty())
                <div class="col m6" style="margin-top: 0.8%;">
                    @foreach($anuncios2 as $anuncio2)
                        <div class="card horizontal">
                        
                            <div class="imagem valign-wrapper">
                                <img src="{{ asset('storage/' . $anuncio2->caminho_imagem) }}">
                            </div>

                            <div class="anuncio">
                                <h6>{{ $anuncio2->nome }}</h6>
                                <div class="card-content anuncio-conteudo">
                                    <p class="flow-text">{{ $anuncio2->descricao }}</p>
                                </div>

                                <div class="anuncio-link">
                                    <div class="col" style="padding-left:0px;">
                                        <a class="tooltipped" data-position="bottom" data-tooltip="Saiba mais" target="_blank" href="http://{{ $anuncio2->link }}"> {{ $anuncio2->nome }} </a>
                                    </div>
                                    
                                    <div class="col right">
                                        <span class="new badge red right-align tooltipped" data-position="bottom" data-tooltip="Data final" data-badge-caption="{{ str_replace('-', '/', date('d-m-Y', strtotime($anuncio1->data_fim))) }}"></span>
                                        <span class="new badge green right-align tooltipped" data-position="bottom" data-tooltip="Data inicial" data-badge-caption="{{ str_replace('-', '/', date('d-m-Y', strtotime($anuncio1->data_inicio))) }}"></span>
                                        @if(Auth::check() && !$trashed)
                                            <span class="tooltipped" data-position="bottom" data-tooltip="Editar anúncio">
                                                <a href="{{ route('anuncio.edit', $anuncio2->id)}}">
                                                    <i class="material-icons">create</i>            
                                                </a>
                                            </span>
                                        @endif

                                        @if(Auth::check() & !$trashed)
                                            <span class="tooltipped" data-position="bottom" data-tooltip="Excluir Anúncio">
                                                    <a href="#" v-on:click = "deleteAd">
                                                        <i class="material-icons right-align">delete</i>
                                                    </a>
                                                <form id = "{{ $anuncio2->id }}" action="{{ route('anuncio.destroy', $anuncio2) }}" method="POST">
                                                    @Method('DELETE')
                                                    @CSRF
                                                </form>
                                            </span>
                                        @endif
                                    </div>
                                    
                                </div>
                            </div>

                        </div>
                    @endforeach
                </div>
            @endif
            
            @if(!$anuncios1->count() && !$anuncios2->count())
                <div class="col m12">
                    <div class="card medium">
                        <div class="card-content">
                            <p>Não há nenhum anúncio cadastrado.<p>
                        </div>  
                    </div>
                </div>
            @endif
            </div>
         
        </div>
@endsection

resources/views/editanuncio.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/anuncio.css') }}">
@endsection

@section('navbar')

    @include('layouts.navbar')

@endsection

@section('content')

<div class="container">  
    <div id="ad">
        <div class="row">

            <div class="col m12">

                <div class="card large">

                    <div class="card-content">
                        <h5>
                            Editar Anúncio
                        </h5>

                        <form action = "{{ route('anuncio.update', $id) }}" method="POST" enctype="multipart/form-data" id ="formulario-anuncio">
                            @csrf
                            @method('PUT')
                            <div class="col m6">

                                <div class="input-field col m12">
                                    <input name="nome" type="text" class="validate" id="nome" value="" v-model="nome">
                                    <label for="nome" id="labelNome">Nome</label>
                                </div>

                                <div class="input-field col m12">
                                    <textarea class="materialize-textarea" name="descricao" id="descricao" v-model="descricao"></textarea>
                                    <label for="textarea1" id="labelDescricao">Descrição do anúncio</label>
                                </div>

                                <div class="input-field col m12">
                                    <input name="link" type="text" value="" v-model="link">
                                    <label id="labelLink" for="link">Link do produto</label>
                                </div>

                            </div>

                            <div class="col m6"> 

                                <div class="file-field input-field col m12">
                                    <div class="btn btn-small orange darken-1 shadow-xm">
                                        <span>Imagem</span>
                                        <input type="file" name="imagem_produto" id="input-image">
                                    </div>

                                    <div class="file-path-wrapper">
                                        <input class="file-path validate" type="text" name="caminho_imagem" id="caminho_imagem" value="" placeholder="Escolha a imagem do produto" v-model="caminho_imagem">
                                    </div>
                                </div>

                                <div class="input-field col s12">
                                    @foreach($estados as $estado)
                                        <div class="col m3">
                                            <p>
                                                <label class="text-orange">
                                                    <input type="checkbox" checked="checked"/>
                                                    <span> {{ $estado }} </span>
                                                </label>
                                            </p>
                                        </div>
                                    @endforeach
                                </div>

                            </div>

                            <div class="col m12 center form-btn">
                                <a v-on:click="showTemplate" class="btn-small orange darken-1"> Pré-visualizar anúncio </a>
                                <a v-on:click="validateAd" class="waves-light btn btn-small orange darken-1"> Cadastrar </a>
                            </div>

                        </form>

                        <div class="col m4 offset-m4" v-if="mostra">
                            
                            <div class="card small">
                                <div class="card-image imagem">
                                    <img class="activator" src="{{ asset($caminho_imagem) }}">
                                </div>

                                <div class="card-content">
                                    <span class="card-title activator grey-text text-darken-4">@{{ nome }}<i class="material-icons right">more_vert</i></span>

                                    <div class="col mt-1">
                                        <a v-bind:href=" 'https://' + link" target="_blank"> @{{ nome }} </a>
                                    </div>

                                    <div class="col right mt-1">
                                        <span class="new badge green right-align tooltipped" data-position="bottom" data-tooltip="Data inicial" v-bind:data-badge-caption="data_criacao"></span>
                                    </div>
                                </div>

                                <div class="card-reveal">
                                    <span class="card-title grey-text text-darken-4">@{{ nome }}<i class="material-icons right">close</i></span>
                                    <p> @{{ descricao }} </p>
                                </div>
                            </div>

                        </div>

                    </div>
                    <input type="hidden" value="{{ $id }}" id="adId">
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/home.css') }}">
@endsection

@section('navbar')

    @include('layouts.navbar')

@endsection

@section('content')
<div class="main">
    <div class="container homeblade">
        <div class="row">
            <h5 class="titleProduto">Lista de Produtos</h5>
            <table class="white z-depth-3 responsive-table highlight">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Descrição</th>
                        <th>Editar</th>
                        <th>Ativo</th>
                    </tr>
                </thead>              
                <tbody class="highlight">
                    @foreach($produtos as $produto)    
                    <tr>
                        <td>{{ $produto -> nome}}</td>
                        <td>{{ $produto -> descricao}}</td>
                        <td><a href="produto/{{ $produto->id}}/edit"><i class="material-icons">create</i></a></td>
                        <td>
                        <p>
                            <label>
                                <input @if((int)$produto->ativo==1) {!! 'checked="checked" ' !!} @endif type="checkbox" class="orange darken-1 filled-in" disabled="disabled" name="ativo" 
                                 value="{{ $produto->ativo }}"/>
                                <span></span>
                            </label>
                         </p>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>    
        </div>
    </div>
</div>
@endsection