routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) 
    {
        return redirect()->route('anuncio.index');
    }

    else
    {
        return view('welcome');
    }
    
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/produto', 'ProdutoController')->middleware('auth');

Route::resource('/anuncio', 'AnuncioController')->middleware('auth');

Route::get('/lixeira', 'AnuncioController@showTrashed')->name('lixeira');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="https://raffinato.inf.br//img/site/980/favicon.png">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="shortcut icon" href="https://raffinato.inf.br//img/site/980/favicon.png">
    @yield('styles')

</head>
<body>
    
    @yield('navbar')

    <!--componente master-->
    <div id="app">

        <main class="py-4">
            @yield('content')
        </main>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    @yield('scripts')

</body>
</html>

resources/views/layouts/navbar.blade.php
@section('navbar')
    <nav class="orange darken-1 shadow-xm">
        <div class="nav-wrapper">
            <div class="row">
                <div class="col m1 offset-m1">
                    <a class="navbar-brand logo" href="#">
                            Raffin<span class="ad">ads</span>
                    </a>
                </div>
                @guest
                    <div class="col m3">
                        <ul>
                            <li>
                                <a class="navbar-brand" href="{{ url('/') }}">
                                    Voltar
                                </a>
                            </li>
                        </ul>
                    </div>
                @else
                    <div class="col m4 valign-wrapper">
                        <ul>
                            <li>
                                <a href="{{ route('anuncio.index') }}">
                                Anúncios
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('anuncio.create') }}">
                                    Cadastrar Anúncio
                                </a>
                            </li>                                                                                
                        </ul>
                    </div>
                    
                    <div class="col m2 offset-m3">
                        <span>
                            Olá, {{ Auth::user()->name }}
                        </span>
                    </div>

                    <div class="col m1">
                        <a class="navbar-brand" href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                            Sair
                        </a>
                    </div>
                
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                @endguest
                
            </div>
        </div>
    </nav>
    
@show